# Generated by Django 3.2.4 on 2021-07-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='img.jpg', upload_to='static'),
        ),
    ]
