# Generated by Django 3.2.4 on 2021-07-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='img.jpg', upload_to='Profile_Images'),
        ),
    ]
